---
apiVersion: v1
kind: Service
metadata:
  name: metrics-services
  labels:
    app: metrics
spec:
  selector:
    metrics: enabled
  ports:
  - name: metrics
    protocol: TCP
    port: 9102
    targetPort: 9102